### ISSUE TITLE
Backend Integration 

### ISSUE THREAD

**Issue by KaiCottle** [KaiCottle/electionCapping24#11]
Setup the Backend Environment:

Set up the project structure for the backend (Node.js, Python, etc.).
Install necessary libraries and dependencies (Express, Flask, ORM like Sequelize, SQLAlchemy, etc.).
 Create Endpoints:

GET: Fetch data from the database for individual records and lists.
Endpoint to fetch all records.
Endpoint to fetch a record by ID.

**Comment by BrendonKupsch1** [comment]
The backend is running perfectly using node express.
