### ISSUE TITLE
User Profile Page (Frontend)

### ISSUE THREAD

**Issue by KaiCottle** [KaiCottle/electionCapping24#14]
We need to create a user profile page for the React project where users can view and edit their information. The profile page should include:

- Displaying user details specified within ERD. 

- An "Edit Profile" button to allow the user to modify details.

- Ensure the design is consistent with the overall application theme and is responsive across devices.

Acceptance Criteria:

- [x] A user profile page is created that displays user information (hardcoded for now, pending backend integration).

- [x] The page includes an "Edit Profile" button.

- [x] The profile details are displayed clearly.

- [ ] The page is responsive and works on all major screen sizes (mobile, tablet, desktop).

**Comment by BrendonKupsch1** [comment]
The user profile page is complete.
