### ISSUE TITLE
User Profile Page Integration (Backend)

### ISSUE THREAD

**Issue by KaiCottle** [KaiCottle/electionCapping24#16]
We need to integrate the user profile page with the backend so users can view and update their personal information. The backend should:

- Provide an API to retrieve user profile information.

- Provide an API to update user profile details.

- Ensure only the authenticated user can access and update their own profile.

- Implement security measures, including token validation for requests.

- For admins, ensure the ability to retrieve and edit any user's profile (optional, based on project requirements).

**Acceptance Criteria:**

- [x] The frontend user profile page successfully fetches user data from the backend.

- [x] The backend returns the correct user data (e.g., name, email, profile picture) based on the authenticated session or token.

- [x] Users can update their profile information, and the backend handles the update correctly.

- [x] Proper security is in place to ensure that only the authenticated user can access and modify their own profile.

- [x] Error handling is in place for unauthorized access, invalid updates, and backend failures.

**Comment by BrendonKupsch1** [comment]
The integration is complete.
