### ISSUE TITLE
SSO Functionality

### ISSUE THREAD

**Issue by KaiCottle** [KaiCottle/electionCapping24#30]
Integrate Single Sign-On (SSO) authentication using Marist College's SSO system. The goal is to enable seamless, secure, and centralized login for users, utilizing Marist's authentication framework for identity verification.

Acceptance Criteria:

Users can authenticate using Marist's SSO.
Successful login redirects users to the main dashboard.
Error handling for failed authentication attempts.
Ensure secure handling of authentication tokens and user sessions.
Adhere to Marist’s SSO security guidelines.

**Comment by BrendonKupsch1** [comment]
SSL for server is now functional, still need to get server running on new domain and create SSO button functionality.

**Comment by BrendonKupsch1** [comment]
Server is running on https, still need to create metadata and send to sso provider. After this the button will be functional.

**Comment by BrendonKupsch1** [comment]
After much research, the SSO button now redirects to Marist's login, and returns to the user-profile page.
